# Generated by Django 6.0.7 on 2026-07-10 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=120)),
                ('semester', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_rate', models.FloatField()),
                ('average_grade', models.FloatField()),
                ('platform_accesses', models.PositiveIntegerField(default=0)),
                ('completed_activities', models.PositiveIntegerField(default=0)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('study_hours_per_week', models.FloatField(default=0)),
                ('dropout_risk', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='students.student')),
            ],
        ),
    ]
